export default[
  { "_id": "A101", "title": "Propulsion Assignment", "course": "RS101" },
  { "_id": "A102", "title": "Combustion Analysis", "course": "RS101" },
  { "_id": "A103", "title": "Nozzle Design Project", "course": "RS101" },
  { "_id": "A201", "title": "Aerodynamics Quiz", "course": "RS102" },
  { "_id": "A202", "title": "Flow Analysis", "course": "RS102" },
  { "_id": "A203", "title": "Heating Analysis", "course": "RS102" },
  { "_id": "A301", "title": "Structural Design Task", "course": "RS103" },
  { "_id": "A302", "title": "Orbital Calculations", "course": "RS103" },
  { "_id": "A303", "title": "Systems Engineering Exam", "course": "RS103" },
  { "_id": "A401", "title": "Organic Nomenclature Practice", "course": "RS104" },
  { "_id": "A402", "title": "Reaction Mechanism Analysis", "course": "RS104" },
  { "_id": "A403", "title": "Spectroscopy Lab Report", "course": "RS104" },
  { "_id": "A404", "title": "Synthesis Project", "course": "RS104" },
  { "_id": "A501", "title": "Coordination Complex Identification", "course": "RS105" },
  { "_id": "A502", "title": "Main Group Chemistry Problem Set", "course": "RS105" },
  { "_id": "A503", "title": "Transition Metal Catalysis Report", "course": "RS105" },
  { "_id": "A504", "title": "Bioinorganic Case Study", "course": "RS105" },
  { "_id": "A601", "title": "Thermodynamics Problem Set", "course": "RS106" },
  { "_id": "A602", "title": "Quantum Mechanics Calculations", "course": "RS106" },
  { "_id": "A603", "title": "Kinetics Lab Report", "course": "RS106" },
  { "_id": "A604", "title": "Statistical Mechanics Exam", "course": "RS106" },
  { "_id": "A701", "title": "Cuneiform Translation Exercise", "course": "RS107" },
  { "_id": "A702", "title": "Ancient Mathematics Analysis", "course": "RS107" },
  { "_id": "A703", "title": "Comparative Civilizations Essay", "course": "RS107" },
  { "_id": "A704", "title": "Archaeological Site Report", "course": "RS107" },
  { "_id": "A801", "title": "Council Simulation Participation", "course": "RS108" },
  { "_id": "A802", "title": "Diplomatic Strategy Paper", "course": "RS108" },
  { "_id": "A803", "title": "Inter-species Relations Analysis", "course": "RS108" },
  { "_id": "A804", "title": "Final Diplomacy Exam", "course": "RS108" }
]